name: "Setup environment"
description: "Setup Node.js, pnpm & install dependencies"
inputs:
  install-modules:
    description: Install node_modules
    default: "true"
runs:
  using: "composite"
  steps:
    - name: pnpm Setup
      uses: pnpm/action-setup@v4
    - name: Node.js Setup
      uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
        cache: "pnpm"
    - name: Install modules
      if: ${{ inputs.install-modules == 'true' }}
      shell: bash
      run: pnpm install --frozen-lockfile
