/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as appSpendingRouteImport } from './routes/(app)/spending'
import { Route as appSaasRouteImport } from './routes/(app)/saas'
import { Route as appHomeRouteImport } from './routes/(app)/home'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const appSpendingRoute = appSpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => appRouteRoute,
} as any)
const appSaasRoute = appSaasRouteImport.update({
  id: '/saas',
  path: '/saas',
  getParentRoute: () => appRouteRoute,
} as any)
const appHomeRoute = appHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/home': typeof appHomeRoute
  '/saas': typeof appSaasRoute
  '/spending': typeof appSpendingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/home': typeof appHomeRoute
  '/saas': typeof appSaasRoute
  '/spending': typeof appSpendingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/(app)/home': typeof appHomeRoute
  '/(app)/saas': typeof appSaasRoute
  '/(app)/spending': typeof appSpendingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/home'
    | '/saas'
    | '/spending'
    | '/auth/callback'
    | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/home'
    | '/saas'
    | '/spending'
    | '/auth/callback'
    | '/auth/register'
  id:
    | '__root__'
    | '/(app)'
    | '/$'
    | '/(app)/home'
    | '/(app)/saas'
    | '/(app)/spending'
    | '/auth/callback'
    | '/auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/spending': {
      id: '/(app)/spending'
      path: '/spending'
      fullPath: '/spending'
      preLoaderRoute: typeof appSpendingRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/saas': {
      id: '/(app)/saas'
      path: '/saas'
      fullPath: '/saas'
      preLoaderRoute: typeof appSaasRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/home': {
      id: '/(app)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof appHomeRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appHomeRoute: typeof appHomeRoute
  appSaasRoute: typeof appSaasRoute
  appSpendingRoute: typeof appSpendingRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appHomeRoute: appHomeRoute,
  appSaasRoute: appSaasRoute,
  appSpendingRoute: appSpendingRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
